apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: test-standard
configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - ENV=overlay-standard